# SearXNG Settings Configuration
# For more settings, see: https://docs.searxng.org/admin/settings/

use_default_settings: true

general:
  instance_name: "AI-Powered Personal Search"
  contact_url: false
  enable_metrics: false
  
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "d0fab1d3884c0ebe80cee38f905663179274286fb59c186ae4abe926dcbdb702"  # This will be replaced by Docker setup
  limiter: true
  image_proxy: true
  method: "GET"
  base_url: false

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  autocomplete_min: 4
  default_lang: "en"
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: true
  infinite_scroll: false
  search_on_category_select: false
  default_theme: "simple"
  center_alignment: true
  hotkeys: "vim"
  
# Categories and search engines
categories_as_tabs:
  general:
    - web
  images:
    - images
  videos:
    - videos
  news:
    - news
  music:
    - music
  it:
    - it
  science:
    - science
  files:
    - files
  social media:
    - social media

# Valkey configuration for caching
valkey:
  url: redis://redis:6379/0

# Privacy and security settings
outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

# Disable engines that don't work well or are problematic
engines:
  - name: arch linux wiki
    disabled: true
  - name: google
    disabled: false
    use_mobile_ui: false
  - name: google images
    disabled: false
  - name: google news
    disabled: false
  - name: google videos
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: duckduckgo images
    disabled: false
  - name: bing
    disabled: false
  - name: bing images
    disabled: false
  - name: bing news
    disabled: false
  - name: bing videos
    disabled: false
  - name: startpage
    disabled: false
  - name: qwant
    disabled: false
  - name: wikipedia
    disabled: false
  - name: wikidata
    disabled: false
  - name: stackoverflow
    disabled: false
  - name: github
    disabled: false
  - name: gitlab
    disabled: false
  - name: codeberg
    disabled: false
  - name: reddit
    disabled: false
  - name: hackernews
    disabled: false
  - name: arxiv
    disabled: false
  - name: currency
    disabled: false
  - name: ddg definitions
    disabled: false

# Locales
locales:
  en: English

# DOI and other resolvers
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://dx.doi.org/'
  doai.io: 'https://doai.io/'
  sci-hub.se: 'https://sci-hub.se/'

default_doi_resolver: 'oadoi.org' 